[config]

[templates.hyprpaper]
input_path = '~/.config/matugen/templates/hyprpaper-template.conf'
output_path = '~/.config/hypr/hyprpaper.conf'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = '~/.config/scripts/hypr_reload_lid.sh'
# post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.wofi]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.tmux/generated.conf'
post_hook = 'tmux source-file ~/.tmux/generated.conf'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim/template.lua'
output_path = '~/.config/nvim/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.spotify_player]
input_path = '~/.config/matugen/templates/spotify-player-theme.toml'
output_path = '~/.config/spotify-player/theme.toml'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.folder]
input_path = '~/.config/matugen/templates/folder-color.txt'
output_path = '~/.config/matugen/papirus-folders/folder-color.txt'
post_hook = '(~/.config/matugen/papirus-folders/change-icons.sh &); killall nautilus'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.sddm]
input_path = '~/.config/matugen/templates/sddm-silent-template.conf'
output_path = '~/.config/matugen/sddm/matugen.conf'

[templates.sddm_script]
input_path = '~/.config/matugen/templates/sddm_theme_copy.sh'
output_path = '~/.config/scripts/sddm_theme_copy.sh'
post_hook = 'sudo /home/seger/.config/scripts/sddm_theme_copy.sh'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spotify-colors.ini'
output_path = '~/.config/spicetify/Themes/Spicetify-retro/color.ini'
post_hook = 'spicetify config current_theme Spicetify-retro; spicetify config color_scheme Matugen; spicetify config inject_theme_js 1; spicetify apply;'
