[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.wofi]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.tmux/generated.conf'
post_hook = 'tmux source-file ~/.tmux/generated.conf'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim/template.lua'
output_path = '~/.config/nvim/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.spotify_player]
input_path = '~/.config/matugen/templates/spotify-player-theme.toml'
output_path = '~/.config/spotify-player/theme.toml'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.slick_greeter]
input_path = '~/.config/matugen/templates/slick-greeter.conf'
output_path = '/etc/lightdm/slick-greeter.conf'
