$schema = 'https://starship.rs/config-schema.json'

format = """
[](color_bg2)\
$os\
$username\
[](bg:color_bg3 fg:color_bg2)\
$directory\
[](fg:color_bg3 bg:color_accent)\
$git_branch\
[](fg:color_accent bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'base16'
#161019
[palettes.base16]
color_bg0 = '#1e1e2e'
color_bg1 = '#313244'
color_bg2 = '#45475a'
color_bg3 = '#6c7086'
color_fg0 = '#a6adc8'
color_fg1 = '#cdd6f4'
color_fg2 = '#f5e0dc'
color_fg3 = '#b4befe'
color_red = '#f38ba8'
color_orange = '#fab387'
color_yellow = '#f9e2af'
color_green = '#a6e3a1'
color_cyan = '#94e2d5'
color_blue = '#89b4fa'
color_magenta = '#cba6f7'
color_brown = '#f2cdcd'
color_accent = '#89b4fa'
error_color = '#f38ba8'

[os]
disabled = false
style = "bg:color_bg2 fg:color_fg1"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_bg2 fg:color_fg1"
style_root = "bg:color_bg2 fg:color_fg1"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_bg3"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_accent"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_accent)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg1 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:color_green)'
error_symbol = '[ ](bold fg:error_color)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_magenta)'
vimcmd_replace_symbol = '[](bold fg:color_magenta)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
