# format = '''
# $directory$git_branch$rust$python
# $character'''
#
# palette = 'colors'
#
# [palettes.colors]
# mustard = '#af8700' # example
# color1 = '#50d8ed'
# color2 = '#00363d'
# color3 = '#bdc7dc'
# color4 = '#1b2029'
# color5 = '#00363d'
# color6 = '#0f141c'
# color7 = '#0f141c'
# color8 = '#50d8ed'
# color9 = '#a7c8ff'
#
# # Prompt symbols 
# [character]
# success_symbol = "[üûà](color9 bold)"
# error_symbol = "[üûà](@{error})"
# vicmd_symbol = "[üûà](#f9e2af)"
#
# [directory]
# format = "[ÓÇ∂](fg:color1 bg:color4)[Û∞âã](bg:color1 fg:color2)[ÓÇ¥ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[ÓÇ¥ ](fg:color4)"
#
# [directory.substitutions]
# "Documents" = "Û∞àô "
# "Downloads" = "ÔÄô "
# "Music" = "ÔÄÅ "
# "Pictures" = "ÔÄæ "
#
# [git_branch]
# format = "[ÓÇ∂](fg:color8 bg:color4)[Ôáì ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "
#
# [time]
# format = "[ÓÇ∂](fg:color8 bg:color4)[Ôê∫ ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "
# disabled = false
# time_format = "%R" # Hour:Minute Format
#
# [python]
# format = "[ÓÇ∂](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "
# symbol = 'üêç'
# # pyenv_version_name = true
# pyenv_prefix = 'venv'

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ÓÇ∂](color2)\
$os\
$username\
[ÓÇ∞](bg:color9 fg:color2)\
$directory\
[ÓÇ∞](fg:color9 bg:color7)\
$git_branch\
[ÓÇ∞](fg:color7 bg:color1)\
$time\
[ÓÇ¥ ](fg:color1)\
$line_break$character"""

palette = 'colors'

[palettes.colors]
color1 = '#001b3c'
color2 = '#001f24'
color3 = '#bdc7dc'
color4 = '#1b2029'
color5 = '#00363d'
color6 = '#0f141c'
color7 = '#05305f'
color8 = '#50d8ed'
color9 = '#004f58'
error_color = '#ffb4ab'
source_color = '#1a5eab'
color_fg0 = '#82d3e2'

[os]
disabled = false
style = "bg:color2 fg:color_fg0"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Û∞£á"
Artix = "Û∞£á"
EndeavourOS = "ÔÜó"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"
Pop = "Ôå™"

[username]
show_always = true
style_user = "bg:color2 fg:color_fg0"
style_root = "bg:color2 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color9"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "‚Ä¶/"


[git_branch]
symbol = "Ôêò"
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color7)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ Ôê∫ $time ](fg:color_fg0 bg:color1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ÔÑÅ](bold fg:source_color)'
error_symbol = '[ ÔÑÅ](bold fg:error_color)'
vimcmd_symbol = '[Ôê¥](bold fg:color_green)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:color_yellow)'

