# Matugen-based theme
[[themes]]
name = "matugen"
[themes.palette]
background = "{{ colors.background.default.hex }}"
foreground = "{{ colors.on_surface.default.hex }}"
black = "{{ colors.surface.default.hex }}"
red = "{{ colors.error.default.hex }}"
green = "{{ colors.primary.default.hex }}"
yellow = "{{ colors.tertiary.default.hex }}"
blue = "{{ colors.on_primary_container.default.hex }}"
magenta = "{{ colors.on_secondary_container.default.hex }}"
cyan = "{{ colors.secondary.default.hex }}"
white = "{{ colors.on_surface.default.hex }}"
bright_black = "{{ colors.surface_bright.default.hex }}"
bright_red = "{{ colors.error.default.hex }}"
bright_green = "{{ colors.primary.default.hex }}"
bright_yellow = "{{ colors.tertiary.default.hex }}"
bright_blue = "{{ colors.on_primary_container.default.hex }}"
bright_magenta = "{{ colors.on_secondary_container.default.hex }}"
bright_cyan = "{{ colors.secondary.default.hex }}"
bright_white = "{{ colors.on_surface.default.hex }}"

[[themes]]
name = "gruvbox_material_hard_dark"
[themes.palette]
background = "#282828"
foreground = "#ddc7a1"
black = "#282828"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
bright_black = "#7c6f64"
bright_red = "#ea6962"
bright_green = "#a9b665"
bright_yellow = "#d8a657"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
bright_cyan = "#89b482"
bright_white = "#d4be98"

