[[themes]]
name = "base16"
[themes.palette]
background = "#222436"
foreground = "#828bb8"
black = "#222436"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffdf77"
blue = "#82aaff"
magenta = "#fca7ea"
cyan = "#86e1fc"
white = "#828bb8"
bright_black = "#3b4261"
bright_red = "#ff757f"
bright_green = "#c3e88d"
bright_yellow = "#ffdf77"
bright_blue = "#82aaff"
bright_magenta = "#fca7ea"
bright_cyan = "#86e1fc"
bright_white = "#c8d3f5"
