# Matugen-based theme
[[themes]]
name = "matugen"
[themes.palette]
background = "#0b160f"
foreground = "#dae6da"
black = "#0b160f"
red = "#ffb4ab"
green = "#cfcb55"
yellow = "#93d5aa"
blue = "#ece76d"
magenta = "#eae68e"
cyan = "#ceca75"
white = "#dae6da"
bright_black = "#313c34"
bright_red = "#ffb4ab"
bright_green = "#cfcb55"
bright_yellow = "#93d5aa"
bright_blue = "#ece76d"
bright_magenta = "#eae68e"
bright_cyan = "#ceca75"
bright_white = "#dae6da"

[[themes]]
name = "gruvbox_material_hard_dark"
[themes.palette]
background = "#282828"
foreground = "#ddc7a1"
black = "#282828"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
bright_black = "#7c6f64"
bright_red = "#ea6962"
bright_green = "#a9b665"
bright_yellow = "#d8a657"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
bright_cyan = "#89b482"
bright_white = "#d4be98"

