[[themes]]
name = "base16"
[themes.palette]
background = "#16172d"
foreground = "#ecf0c1"
black = "#16172d"
red = "#e33400"
green = "#5ccc96"
yellow = "#f2ce00"
blue = "#7a5ccc"
magenta = "#b3a1e6"
cyan = "#00a3cc"
white = "#ecf0c1"
bright_black = "#686f9a"
bright_red = "#e33400"
bright_green = "#5ccc96"
bright_yellow = "#f2ce00"
bright_blue = "#7a5ccc"
bright_magenta = "#b3a1e6"
bright_cyan = "#00a3cc"
bright_white = "#ffffff"
