[[themes]]
name = "base16"
[themes.palette]
background = "#f2e5bc"
foreground = "#504945"
black = "#f2e5bc"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#504945"
bright_black = "#bdae93"
bright_red = "#9d0006"
bright_green = "#79740e"
bright_yellow = "#b57614"
bright_blue = "#076678"
bright_magenta = "#8f3f71"
bright_cyan = "#427b58"
bright_white = "#282828"
