# Matugen-based theme
[[themes]]
name = "matugen"
[themes.palette]
background = "#091517"
foreground = "#d7e5e7"
black = "#091517"
red = "#ffb4ab"
green = "#7eda9a"
yellow = "#81d3dd"
blue = "#99f6b4"
magenta = "#b2f1c0"
cyan = "#96d5a6"
white = "#d7e5e7"
bright_black = "#2f3b3d"
bright_red = "#ffb4ab"
bright_green = "#7eda9a"
bright_yellow = "#81d3dd"
bright_blue = "#99f6b4"
bright_magenta = "#b2f1c0"
bright_cyan = "#96d5a6"
bright_white = "#d7e5e7"

[[themes]]
name = "gruvbox_material_hard_dark"
[themes.palette]
background = "#282828"
foreground = "#ddc7a1"
black = "#282828"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
bright_black = "#7c6f64"
bright_red = "#ea6962"
bright_green = "#a9b665"
bright_yellow = "#d8a657"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
bright_cyan = "#89b482"
bright_white = "#d4be98"

