[[themes]]
name = "base16"
[themes.palette]
background = "#000000"
foreground = "#c1c1c1"
black = "#000000"
red = "#5f8787"
green = "#ddeecc"
yellow = "#99bbaa"
blue = "#888888"
magenta = "#999999"
cyan = "#aaaaaa"
white = "#c1c1c1"
bright_black = "#333333"
bright_red = "#5f8787"
bright_green = "#ddeecc"
bright_yellow = "#99bbaa"
bright_blue = "#888888"
bright_magenta = "#999999"
bright_cyan = "#aaaaaa"
bright_white = "#c1c1c1"
