# Matugen-based theme
[[themes]]
name = "matugen"
[themes.palette]
background = "#0f141c"
foreground = "#dee2ef"
black = "#0f141c"
red = "#ffb4ab"
green = "#50d8ed"
yellow = "#a7c8ff"
blue = "#9cefff"
magenta = "#9eeffe"
cyan = "#82d3e2"
white = "#dee2ef"
bright_black = "#343943"
bright_red = "#ffb4ab"
bright_green = "#50d8ed"
bright_yellow = "#a7c8ff"
bright_blue = "#9cefff"
bright_magenta = "#9eeffe"
bright_cyan = "#82d3e2"
bright_white = "#dee2ef"

[[themes]]
name = "gruvbox_material_hard_dark"
[themes.palette]
background = "#282828"
foreground = "#ddc7a1"
black = "#282828"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
bright_black = "#7c6f64"
bright_red = "#ea6962"
bright_green = "#a9b665"
bright_yellow = "#d8a657"
bright_blue = "#7daea3"
bright_magenta = "#d3869b"
bright_cyan = "#89b482"
bright_white = "#d4be98"

