[[kitty]]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[[hyprpaper]]
input_path = 'templates/hyprpaper.conf'
output_path = '~/.config/hypr/hyprpaper.conf'

[[hyprland]]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = '~/.config/scripts/hypr_reload_lid.sh'

[[waybar]]
input_path = 'templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[[wofi]]
input_path = 'templates/colors.css'
output_path = '~/.config/wofi/colors.css'

# [[starship]]
# input_path = 'templates/starship-colors.toml'
# output_path = '~/.config/starship.toml'

[[tmux]]
input_path = 'templates/tmux-colors.conf'
output_path = '~/.tmux/generated.conf'
post_hook = 'tmux source-file ~/.tmux/generated.conf'

[[neovim]]
input_path = 'templates/neovim-colors.lua'
output_path = '~/.config/nvim/colors.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[[spotify_player]]
input_path = 'templates/spotify-player-theme.toml'
output_path = '~/.config/spotify-player/theme.toml'

[[gtk3]]
input_path = 'templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[[gtk4]]
input_path = 'templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[[yazi]]
input_path = 'templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[[sddm]]
input_path = 'templates/sddm-silent-template.conf'
output_path = '~/.config/theme-switcher-sddm/sddm.conf'

[[sddm_script]]
input_path = 'templates/sddm_theme_copy.sh'
output_path = '~/.config/scripts/sddm_theme_copy.sh'
post_hook = '(sleep 2 && sudo /home/seger/.config/scripts/sddm_theme_copy.sh) &'

# [[spicetify]]
# input_path = 'templates/spotify-colors.ini'
# output_path = '~/.config/spicetify/Themes/Spicetify-retro/color.ini'
# post_hook = '((spicetify config current_theme Spicetify-retro; spicetify config color_scheme base16; spicetify config inject_theme_js 1; spicetify apply -n; pgrep -x spotify >/dev/null && spicetify restart;) &)'

[[folder]]
input_path = 'templates/folder-color.txt'
output_path = '~/.config/scripts/theme-switcher/current-theme/folder-color.txt'
post_hook = 'killall nautilus; nohup ~/.config/scripts/theme-switcher/change_icons.py >/dev/null 2>&1 &'

[[obsidian]]
input_path = 'templates/obsidian-minimal-colors.css'
output_path = '~/.config/obsidian-customization/.obsidian/snippets/obsidian-minimal-snippet.css'
